/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.51
 * Generated at: 2020-04-18 01:04:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _3aadded_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1.0\"/>\r\n");
      out.write("        <title>NatPro - Materialize</title>\r\n");
      out.write("\r\n");
      out.write("        <!-- CSS  -->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"css/materialize.css\" type=\"text/css\" rel=\"stylesheet\" media=\"screen,projection\"/>\r\n");
      out.write("        <link href=\"css/style.css\" type=\"text/css\" rel=\"stylesheet\" media=\"screen,projection\"/>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <nav class=\"white\" role=\"navigation\">\r\n");
      out.write("            <div class=\"nav-wrapper container\"><a id=\"logo-container\" href=\"#\" class=\"brand-logo\">NatPro</a>\r\n");
      out.write("                <ul class=\"right hide-on-med-and-down\">\r\n");
      out.write("                    <li><a href=\"1mainpage.jsp\">Home</a></li>\r\n");
      out.write("                    <li><a href=\"2upload.jsp\">Upload</a></li>\r\n");
      out.write("                    <li><a href=\"3add.jsp\" class=\"white-text green darken-3\">Add</a></li>\r\n");
      out.write("                    <li><a href=\"4validation.jsp\">Validation</a></li>\r\n");
      out.write("                    <li><a href=\"5search.jsp\">Search</a></li>\r\n");
      out.write("                    <li><a href=\"6view.jsp\">View</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("                <ul id=\"nav-mobile\" class=\"sidenav\">\r\n");
      out.write("                    <li><a href=\"1mainpage.jsp\">Home</a></li>\r\n");
      out.write("                    <li><a href=\"2upload.jsp\">Upload</a></li>\r\n");
      out.write("                    <li><a href=\"3add.jsp\" class=\"white-text green darken-3\">Add</a></li>\r\n");
      out.write("                    <li><a href=\"4validation.jsp\">Validation</a></li>\r\n");
      out.write("                    <li><a href=\"5search.jsp\">Search</a></li>\r\n");
      out.write("                    <li><a href=\"6view.jsp\">View</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <a href=\"#\" data-target=\"nav-mobile\" class=\"sidenav-trigger\"><i class=\"material-icons\">menu</i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"section no-pad-bot green darken-1\" id=\"index-banner\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!--<br><br>-->\r\n");
      out.write("                <h1 class=\"header center white-text\">Add</h1>\r\n");
      out.write("                <div class=\"row center white-text\">\r\n");
      out.write("                    <h6>Successfully added a plant</h6>\r\n");
      out.write("                    <a class=\"btn waves-effect waves-light green accent-4\" href=\"4validation.jsp\">Validate added data</a>\r\n");
      out.write("                    <a class=\"btn waves-effect waves-light green accent-4\" href=\"3add.jsp\">add another entry</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br><br>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section\">\r\n");
      out.write("\r\n");
      out.write("                <!--   Icon Section   -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col s12 m4\">\r\n");
      out.write("                        <div class=\"icon-block\">\r\n");
      out.write("                            <h2 class=\"center light-blue-text\"><i class=\"material-icons\">flash_on</i></h2>\r\n");
      out.write("                            <h5 class=\"center\">Speeds up development</h5>\r\n");
      out.write("\r\n");
      out.write("                            <p class=\"light\">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col s12 m4\">\r\n");
      out.write("                        <div class=\"icon-block\">\r\n");
      out.write("                            <h2 class=\"center light-blue-text\"><i class=\"material-icons\">group</i></h2>\r\n");
      out.write("                            <h5 class=\"center\">User Experience Focused</h5>\r\n");
      out.write("\r\n");
      out.write("                            <p class=\"light\">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col s12 m4\">\r\n");
      out.write("                        <div class=\"icon-block\">\r\n");
      out.write("                            <h2 class=\"center light-blue-text\"><i class=\"material-icons\">settings</i></h2>\r\n");
      out.write("                            <h5 class=\"center\">Easy to work with</h5>\r\n");
      out.write("\r\n");
      out.write("                            <p class=\"light\">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <br><br>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <footer class=\"page-footer green darken-3\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col l6 s12\">\r\n");
      out.write("                    <h5 class=\"white-text\">Company Bio</h5>\r\n");
      out.write("                    <p class=\"grey-text text-lighten-4\">We are a team of college students who are working on this prototype.</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col l3 s12\">\r\n");
      out.write("                        <h5 class=\"white-text\">Team</h5>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a class=\"white-text\" href=\"#!\">Altea</a></li>\r\n");
      out.write("                            <li><a class=\"white-text\" href=\"#!\">Dagdag</a></li>\r\n");
      out.write("                            <li><a class=\"white-text\" href=\"#!\">Embestro</a></li>\r\n");
      out.write("                            <li><a class=\"white-text\" href=\"#!\">Ong</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-copyright green darken-4\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    Made by <a class=\"orange-text text-lighten-3\" href=\"http://materializecss.com\">Materialize</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!--  Scripts-->\r\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("        <script src=\"js/materialize.js\"></script>\r\n");
      out.write("        <script src=\"js/init.js\"></script>\r\n");
      out.write("        <script>\r\n");
      out.write("            $(document).ready(function(){\r\n");
      out.write("                $('select').formSelect();\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
