/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.51
 * Generated at: 2020-03-16 09:04:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _5search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1.0\"/>\r\n");
      out.write("        <title>NatPro - Materialize</title>\r\n");
      out.write("\r\n");
      out.write("        <!-- CSS  -->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"css/materialize.css\" type=\"text/css\" rel=\"stylesheet\" media=\"screen,projection\"/>\r\n");
      out.write("        <link href=\"css/style.css\" type=\"text/css\" rel=\"stylesheet\" media=\"screen,projection\"/>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <nav class=\"white\" role=\"navigation\">\r\n");
      out.write("            <div class=\"nav-wrapper container\"><a id=\"logo-container\" href=\"#\" class=\"brand-logo\">NatPro</a>\r\n");
      out.write("                <ul class=\"right hide-on-med-and-down\">\r\n");
      out.write("                    <li><a href=\"1mainpage.jsp\">Home</a></li>\r\n");
      out.write("                    <li><a href=\"2upload.jsp\">Upload</a></li>\r\n");
      out.write("                    <li><a href=\"3add.jsp\">Add</a></li>\r\n");
      out.write("                    <li><a href=\"4validation.jsp\">Validation</a></li>\r\n");
      out.write("                    <li><a href=\"5search.jsp\" class=\"white-text green darken-3\">Search</a></li>\r\n");
      out.write("                    <li><a href=\"6view.jsp\">View</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("                <ul id=\"nav-mobile\" class=\"sidenav\">\r\n");
      out.write("                    <li><a href=\"1mainpage.jsp\">Home</a></li>\r\n");
      out.write("                    <li><a href=\"2upload.jsp\">Upload</a></li>\r\n");
      out.write("                    <li><a href=\"3add.jsp\">Add</a></li>\r\n");
      out.write("                    <li><a href=\"4validation.jsp\">Validation</a></li>\r\n");
      out.write("                    <li><a href=\"5search.jsp\" class=\"white-text green darken-3\">Search</a></li>\r\n");
      out.write("                    <li><a href=\"6view.jsp\">View</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <a href=\"#\" data-target=\"nav-mobile\" class=\"sidenav-trigger\"><i class=\"material-icons\">menu</i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"section no-pad-bot\" id=\"index-banner\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!--<br><br>-->\r\n");
      out.write("                <h1 class=\"header center green-text text-darken-3\">Search</h1>\r\n");
      out.write("                <div class=\"row center\">\r\n");
      out.write("                    <h6>Search for plants, chemical compound, etc.</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                \t<a class=\"col s3 offset-s9 waves-effect waves-light btn green darken-3\" onclick=\"switchSearch()\" id=\"switchSearch\">Switch to advanced search</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <form class=\"row\" action=\"5asearchresults.jsp\" id=\"normSearch\">\r\n");
      out.write("                    <div class=\"input-field col s9\">\r\n");
      out.write("                        <i class=\"material-icons prefix\">search</i>\r\n");
      out.write("                        <input id=\"searchInput\" class=\"materialize-textarea\" type=\"text\">\r\n");
      out.write("                        <label for=\"searchInput\">Search</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"input-field col s3\">\r\n");
      out.write("                        <select class=\"browser-default\">\r\n");
      out.write("                            <option value=\"\" disabled selected>Choose your option</option>\r\n");
      out.write("                            <option value=\"1\">plant common name</option>\r\n");
      out.write("                            <option value=\"2\">plant scientific name</option>\r\n");
      out.write("                            <option value=\"3\">genus</option>\r\n");
      out.write("                            <option value=\"4\">family</option>\r\n");
      out.write("                            <option value=\"5\">chemical compound</option>\r\n");
      out.write("                            <option value=\"6\">location</option>\r\n");
      out.write("                            <option value=\"7\">biological activites</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <input type=\"submit\" class=\"waves-effect waves-light btn center green darken-3 col s4 offset-s4\" id=\"btnSubmit\" value=\"search\">\r\n");
      out.write("                </form>\r\n");
      out.write("                <form id=\"advSearch\" action=\"\" class=\"row\" hidden>\r\n");
      out.write("                \t<div class=\"input-field col s12\">\r\n");
      out.write("                        <i class=\"material-icons prefix\">search</i>\r\n");
      out.write("                        <input id=\"searchInput\" class=\"materialize-textarea\" type=\"text\">\r\n");
      out.write("                        <label for=\"searchInput\">Search for anything</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                    \t<h6>Limit search for only:</h6><br>\r\n");
      out.write("                    \t<label class=\"\">\r\n");
      out.write("                    \t\t<input type=\"checkbox\" class=\"filled-in\">\r\n");
      out.write("                    \t\t<span style=\"padding-right: 20px;\">Scientific Plant Name</span>\r\n");
      out.write("                    \t</label>\r\n");
      out.write("                    \t<label class=\"\">\r\n");
      out.write("                    \t\t<input type=\"checkbox\" class=\"filled-in\">\r\n");
      out.write("                    \t\t<span style=\"padding-right: 20px;\">Common Plant Name</span>\r\n");
      out.write("                    \t</label>\r\n");
      out.write("                    \t<label class=\"\">\r\n");
      out.write("                    \t\t<input type=\"checkbox\" class=\"filled-in\">\r\n");
      out.write("                    \t\t<span style=\"padding-right: 20px;\">Genus</span>\r\n");
      out.write("                    \t</label>\r\n");
      out.write("                    \t<label class=\"\">\r\n");
      out.write("                    \t\t<input type=\"checkbox\" class=\"filled-in\">\r\n");
      out.write("                    \t\t<span style=\"padding-right: 20px;\">Family</span>\r\n");
      out.write("                    \t</label>\r\n");
      out.write("                    \t<label class=\"\">\r\n");
      out.write("                    \t\t<input type=\"checkbox\" class=\"filled-in\">\r\n");
      out.write("                    \t\t<span style=\"padding-right: 20px;\">Chemical Compound</span>\r\n");
      out.write("                    \t</label>\r\n");
      out.write("                    \t<label class=\"\">\r\n");
      out.write("                    \t\t<input type=\"checkbox\" class=\"filled-in\">\r\n");
      out.write("                    \t\t<span style=\"padding-right: 20px;\">Location</span>\r\n");
      out.write("                    \t</label>\r\n");
      out.write("                    \t<label class=\"\">\r\n");
      out.write("                    \t\t<input type=\"checkbox\" class=\"filled-in\">\r\n");
      out.write("                    \t\t<span style=\"padding-right: 20px;\">Biological Activites</span>\r\n");
      out.write("                    \t</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                    \t<h6>Plant Part Usage: </h6><br>\r\n");
      out.write("                    \t\r\n");
      out.write("                    \t<!-- \r\n");
      out.write("\t                    \t<div class=\"input-field col s8\">\r\n");
      out.write("\t\t                        <i class=\"material-icons prefix\">search</i>\r\n");
      out.write("\t\t                        <input id=\"searchInput\" class=\"materialize-textarea\" type=\"text\">\r\n");
      out.write("\t\t                        <label for=\"searchInput\">Search</label>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                    <div class=\"col s1\">\r\n");
      out.write("\t\t                    \t<h6>for</h6>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t                    -->\r\n");
      out.write("\t                    <div class=\"col s1\" style=\"padding-top: 15px\">\r\n");
      out.write("\t                    \t<h6>Use</h6>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <!-- should get values from orgpart.text and procedurally generated every time search is called -->\r\n");
      out.write("\t                    <div class=\"input-field col s5\">\r\n");
      out.write("\t                        <select class=\"browser-default\">\r\n");
      out.write("\t                            <option value=\"\" disabled selected>Choose plant part</option>\r\n");
      out.write("\t                            <option value=\"1\">Aerial Plant Parts</option>\r\n");
      out.write("\t                            <option value=\"2\">Petiole and Rachis</option>\r\n");
      out.write("\t                            <option value=\"3\">Unripe Sarcotesta</option>\r\n");
      out.write("\t                            <option value=\"4\">Aerial Plant Part</option>\r\n");
      out.write("\t                            <option value=\"5\">Ripe Sarcotesta</option>\r\n");
      out.write("\t                            <option value=\"6\">Fruiting Bodies</option>\r\n");
      out.write("\t                            <option value=\"7\">Fruiting Body</option>\r\n");
      out.write("\t                            <option value=\"8\">Aerial Parts</option>\r\n");
      out.write("\t                            <option value=\"9\">Female Cone</option>\r\n");
      out.write("\t                            <option value=\"10\">Aerial Part</option>\r\n");
      out.write("\t                            <option value=\"11\">Fruit Rinds</option>\r\n");
      out.write("\t                            <option value=\"12\">Sclerotesta</option>\r\n");
      out.write("\t                            <option value=\"13\">Sarcotesta</option>\r\n");
      out.write("\t                            <option value=\"14\">Fruit Rind</option>\r\n");
      out.write("\t                            <option value=\"15\">Male Cone</option>\r\n");
      out.write("\t                            <option value=\"16\">Stem Bark</option>\r\n");
      out.write("\t                            <option value=\"17\">Cone Base</option>\r\n");
      out.write("\t                            <option value=\"18\">Endotesta</option>\r\n");
      out.write("\t                            <option value=\"19\">Flowers</option>\r\n");
      out.write("\t                            <option value=\"20\">Leaflet</option>\r\n");
      out.write("\t                            <option value=\"21\">Flower</option>\r\n");
      out.write("\t                            <option value=\"22\">Fruits</option>\r\n");
      out.write("\t                            <option value=\"23\">Trunks</option>\r\n");
      out.write("\t                            <option value=\"24\">Leaves</option>\r\n");
      out.write("\t                            <option value=\"25\">Fruit</option>\r\n");
      out.write("\t                            <option value=\"26\">Trunk</option>\r\n");
      out.write("\t                            <option value=\"27\">Seeds</option>\r\n");
      out.write("\t                            <option value=\"28\">Roots</option>\r\n");
      out.write("\t                            <option value=\"29\">Twigs</option>\r\n");
      out.write("\t                            <option value=\"30\">Stems</option>\r\n");
      out.write("\t                            <option value=\"31\">Seed</option>\r\n");
      out.write("\t                            <option value=\"32\">Root</option>\r\n");
      out.write("\t                            <option value=\"33\">Twig</option>\r\n");
      out.write("\t                            <option value=\"34\">Stem</option>\r\n");
      out.write("\t                            <option value=\"35\">Pods</option>\r\n");
      out.write("\t                            <option value=\"36\">Leaf</option>\r\n");
      out.write("\t                            <option value=\"37\">Bark</option>\r\n");
      out.write("\t                            <option value=\"38\">Pod</option>\r\n");
      out.write("\t                        </select>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"col s1\"  style=\"padding-top: 15px\">\r\n");
      out.write("\t                    \t<h6>to</h6>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <!-- should get values from bodypart.text and procedurally generated every time search is called -->\r\n");
      out.write("\t                    <div class=\"input-field col s5\">\r\n");
      out.write("\t                        <select class=\"browser-default\">\r\n");
      out.write("\t                            <option value=\"\" disabled selected>Choose body part</option>\r\n");
      out.write("\t                            <option value=\"1\">Gall Bladder</option>\r\n");
      out.write("\t                            <option value=\"2\">Intestines</option>\r\n");
      out.write("\t                            <option value=\"3\">Esophagus</option>\r\n");
      out.write("\t                            <option value=\"4\">Intestine</option>\r\n");
      out.write("\t                            <option value=\"5\">Shoulders</option>\r\n");
      out.write("\t                            <option value=\"6\">Buttocks</option>\r\n");
      out.write("\t                            <option value=\"7\">Bladder</option>\r\n");
      out.write("\t                            <option value=\"8\">Kidneys</option>\r\n");
      out.write("\t                            <option value=\"9\">Ovaries</option>\r\n");
      out.write("\t                            <option value=\"10\">Stomach</option>\r\n");
      out.write("\t                            <option value=\"11\">Thyroid</option>\r\n");
      out.write("\t                            <option value=\"12\">Fingers</option>\r\n");
      out.write("\t                            <option value=\"13\">Breasts</option>\r\n");
      out.write("\t                            <option value=\"14\">Abdomen</option>\r\n");
      out.write("\t                            <option value=\"15\">Kidney</option>\r\n");
      out.write("\t                            <option value=\"16\">Spleen</option>\r\n");
      out.write("\t                            <option value=\"17\">Thymus</option>\r\n");
      out.write("\t                            <option value=\"18\">Cheeks</option>\r\n");
      out.write("\t                            <option value=\"19\">Tongue</option>\r\n");
      out.write("\t                            <option value=\"20\">Throat</option>\r\n");
      out.write("\t                            <option value=\"21\">Elbows</option>\r\n");
      out.write("\t                            <option value=\"22\">Wrists</option>\r\n");
      out.write("\t                            <option value=\"23\">Finger</option>\r\n");
      out.write("\t                            <option value=\"24\">Breat</option>\r\n");
      out.write("\t                            <option value=\"25\">Thighs</option>\r\n");
      out.write("\t                            <option value=\"26\">Calves</option>\r\n");
      out.write("\t                            <option value=\"27\">Ankles</option>\r\n");
      out.write("\t                            <option value=\"28\">Brain</option>\r\n");
      out.write("\t                            <option value=\"29\">Heart</option>\r\n");
      out.write("\t                            <option value=\"30\">Liver</option>\r\n");
      out.write("\t                            <option value=\"31\">Lungs</option>\r\n");
      out.write("\t                            <option value=\"32\">Ovary</option>\r\n");
      out.write("\t                            <option value=\"33\">Veins</option>\r\n");
      out.write("\t                            <option value=\"34\">Cheek</option>\r\n");
      out.write("\t                            <option value=\"35\">Mouth</option>\r\n");
      out.write("\t                            <option value=\"36\">Teeth</option>\r\n");
      out.write("\t                            <option value=\"37\">Tooth</option>\r\n");
      out.write("\t                            <option value=\"38\">Elbow</option>\r\n");
      out.write("\t                            <option value=\"39\">Wrist</option>\r\n");
      out.write("\t                            <option value=\"40\">Hands</option>\r\n");
      out.write("\t                            <option value=\"41\">Spine</option>\r\n");
      out.write("\t                            <option value=\"42\">Chest</option>\r\n");
      out.write("\t                            <option value=\"43\">Navel</option>\r\n");
      out.write("\t                            <option value=\"44\">Thigh</option>\r\n");
      out.write("\t                            <option value=\"45\">Knees</option>\r\n");
      out.write("\t                            <option value=\"46\">Heels</option>\r\n");
      out.write("\t                            <option value=\"47\">Ankle</option>\r\n");
      out.write("\t                            <option value=\"48\">Eyes</option>\r\n");
      out.write("\t                            <option value=\"49\">Vein</option>\r\n");
      out.write("\t                            <option value=\"50\">Head</option>\r\n");
      out.write("\t                            <option value=\"51\">Jaw</option>\r\n");
      out.write("\t                            <option value=\"52\">Chin</option>\r\n");
      out.write("\t                            <option value=\"53\">Ears</option>\r\n");
      out.write("\t                            <option value=\"54\">Nose</option>\r\n");
      out.write("\t                            <option value=\"55\">Neck</option>\r\n");
      out.write("\t                            <option value=\"56\">Arms</option>\r\n");
      out.write("\t                            <option value=\"57\">Hand</option>\r\n");
      out.write("\t                            <option value=\"58\">Hips</option>\r\n");
      out.write("\t                            <option value=\"59\">Legs</option>\r\n");
      out.write("\t                            <option value=\"60\">Knee</option>\r\n");
      out.write("\t                            <option value=\"61\">Calf</option>\r\n");
      out.write("\t                            <option value=\"62\">Heel</option>\r\n");
      out.write("\t                            <option value=\"63\">Foot</option>\r\n");
      out.write("\t                            <option value=\"64\">Feet</option>\r\n");
      out.write("\t                            <option value=\"65\">Toes</option>\r\n");
      out.write("\t                            <option value=\"66\">Eye</option>\r\n");
      out.write("\t                            <option value=\"67\">Jaw</option>\r\n");
      out.write("\t                            <option value=\"68\">Ear</option>\r\n");
      out.write("\t                            <option value=\"69\">Arm</option>\r\n");
      out.write("\t                            <option value=\"70\">Hip</option>\r\n");
      out.write("\t                            <option value=\"71\">Leg</option>\r\n");
      out.write("\t                            <option value=\"72\">Toe</option>\r\n");
      out.write("\t                        </select>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <input type=\"submit\" class=\"waves-effect waves-light btn center green darken-3 col s4 offset-s4\" id=\"btnSubmit\" value=\"search\">\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section\">\r\n");
      out.write("\r\n");
      out.write("                <!--   Icon Section   -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col s12 m4\">\r\n");
      out.write("                        <div class=\"icon-block\">\r\n");
      out.write("                            <h2 class=\"center light-blue-text\"><i class=\"material-icons\">flash_on</i></h2>\r\n");
      out.write("                            <h5 class=\"center\">Speeds up development</h5>\r\n");
      out.write("\r\n");
      out.write("                            <p class=\"light\">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col s12 m4\">\r\n");
      out.write("                        <div class=\"icon-block\">\r\n");
      out.write("                            <h2 class=\"center light-blue-text\"><i class=\"material-icons\">group</i></h2>\r\n");
      out.write("                            <h5 class=\"center\">User Experience Focused</h5>\r\n");
      out.write("\r\n");
      out.write("                            <p class=\"light\">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col s12 m4\">\r\n");
      out.write("                        <div class=\"icon-block\">\r\n");
      out.write("                            <h2 class=\"center light-blue-text\"><i class=\"material-icons\">settings</i></h2>\r\n");
      out.write("                            <h5 class=\"center\">Easy to work with</h5>\r\n");
      out.write("\r\n");
      out.write("                            <p class=\"light\">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <br><br>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <footer class=\"page-footer green darken-3\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col l6 s12\">\r\n");
      out.write("                    <h5 class=\"white-text\">Company Bio</h5>\r\n");
      out.write("                    <p class=\"grey-text text-lighten-4\">We are a team of college students who are working on this prototype.</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col l3 s12\">\r\n");
      out.write("                        <h5 class=\"white-text\">Team</h5>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a class=\"white-text\" href=\"#!\">Altea</a></li>\r\n");
      out.write("                            <li><a class=\"white-text\" href=\"#!\">Dagdag</a></li>\r\n");
      out.write("                            <li><a class=\"white-text\" href=\"#!\">Embestro</a></li>\r\n");
      out.write("                            <li><a class=\"white-text\" href=\"#!\">Ong</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-copyright green darken-4\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    Made by <a class=\"orange-text text-lighten-3\" href=\"http://materializecss.com\">Materialize</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!--  Scripts-->\r\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("        <script src=\"js/materialize.js\"></script>\r\n");
      out.write("        <script src=\"js/init.js\"></script>\r\n");
      out.write("        <script>\r\n");
      out.write("            $(document).ready(function() {\r\n");
      out.write("                $('select').formSelect();\r\n");
      out.write("            })\r\n");
      out.write("            \r\n");
      out.write("            function switchSearch() {\r\n");
      out.write("            \tvar nSearch = document.getElementById(\"normSearch\");\r\n");
      out.write("            \tvar aSearch = document.getElementById(\"advSearch\");\r\n");
      out.write("            \tvar sSearch = document.getElementById(\"switchSearch\");\r\n");
      out.write("            \t\r\n");
      out.write("            \tif (nSearch.style.display == \"none\" && aSearch.style.display == \"block\") {\r\n");
      out.write("            \t\taSearch.style.display = \"none\";\r\n");
      out.write("            \t\tnSearch.style.display = \"block\";\r\n");
      out.write("            \t\tsSearch.textContent = \"switch to advanced search\";\r\n");
      out.write("            \t}\r\n");
      out.write("            \telse {\r\n");
      out.write("            \t\taSearch.style.display = \"block\";\r\n");
      out.write("            \t\tnSearch.style.display = \"none\";\r\n");
      out.write("            \t\tsSearch.textContent = \"switch to normal search\";\r\n");
      out.write("            \t}\r\n");
      out.write("            \t\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
